# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: playground-app
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/Ziko909/Inception-of-Things.git
#     targetRevision: HEAD
#     path: p3/confs/app
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: dev
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true




apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://167.172.153.84:8081/root/skasmi2.git
    targetRevision: main
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: playground  # Updated to use the 'playground' namespace created by your script
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

