apiVersion: v1
kind: Service
metadata:
  name: service-gitlab
  namespace: gitlab
spec:
  selector:
    app: gitlab-local
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer